---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

commonLabels:
  app.kubernetes.io/name: keycloak

images:
  - name: keycloak-checks
    newName: webhippie/alpine
    newTag: "3.14"

  - name: keycloak-server
    newName: quay.io/keycloak/keycloak
    newTag: "12.0.4"
  - name: keycloak-extensions
    newName: quay.io/keycloak/keycloak-init-container
    newTag: "12.0.4"

...
