---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

images:
  - name: keycloak-checks
    newName: quay.io/webhippie/alpine
    newTag: "3.15"
  - name: keycloak-extensions
    newName: quay.io/keycloak/keycloak-init-container
    newTag: "18.0.0"
  - name: keycloak-server
    newName: quay.io/keycloak/keycloak
    newTag: "18.0.2"

...
