---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

images:
  - name: keycloak-checks
    newName: quay.io/webhippie/alpine
    newTag: "3.20"
  - name: keycloak-extensions
    newName: quay.io/keycloak/keycloak-init-container
    newTag: "19.0.3"
  - name: keycloak-server
    newName: quay.io/keycloak/keycloak
    newTag: "26.0.5"

...
