---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - service.yml
  - statefulset.yml

commonLabels:
  app.kubernetes.io/component: server

configMapGenerator:
  - name: keycloak-server
    literals:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres-server
      - DB_PORT=5432
      - DB_DATABASE=keycloak
  - name: keycloak-extension
    literals:
      - KEYCLOAK_EXTENSIONS=https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.1.0/keycloak-metrics-spi-2.1.0.jar
  - name: keycloak-startup
    files:
      - keycloak.cli=keycloak.cli

...
