---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: keycloak-server
    options:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: server
    literals:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres-server
      - DB_PORT=5432
      - DB_DATABASE=keycloak
  - name: keycloak-extension
    options:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: server
    literals:
      - KEYCLOAK_EXTENSIONS=https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.1/keycloak-metrics-spi-2.5.1.jar
  - name: keycloak-startup
    options:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: server
    files:
      - configs/keycloak.cli

secretGenerator:
  - name: keycloak-server
    options:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: server
    literals: []

...
